    <!-- jQuery Scripts -->
    <script src="<?= asset('js/jquery.min.js') ?>"></script>
    <script src="<?= asset('js/bootstrap.min.js') ?>"></script>
    <script src="<?= asset('js/easing.min.js') ?>"></script>
    <script src="<?= asset('js/owl-carousel.min.js') ?>"></script>
    <script src="<?= asset('js/flickity.pkgd.min.js') ?>"></script>
    <script src="<?= asset('js/twitterFetcher_min.js') ?>"></script>
    <script src="<?= asset('js/jquery.newsTicker.min.js') ?>"></script>
    <script src="<?= asset('js/modernizr.min.js') ?>"></script>
    <script src="<?= asset('js/scripts.js') ?>"></script>